In [2]:
import numpy as np

In [3]:
# Q.17
even = [i**2 for i in range(2 ,10, 2)]
print(even)

[4, 16, 36, 64]


In [4]:
# Q.18
import numpy as np
arr= np.random.randint(0,9,size=(3,3))
arr

array([[0, 1, 0],
       [1, 7, 0],
       [0, 7, 2]], dtype=int32)

In [5]:
# Q.19
max_value= [1,3,56,3,4,63]
print(max(max_value))

63


In [6]:
# Q.20
list_data = [5, 10, 15, 20]
for idx, value in enumerate(list_data):
    print(idx, value)
    

0 5
1 10
2 15
3 20


In [7]:
# Q.22
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

# Example: create a zeros array of the same shape as arr
zeros_arr = np.zeros(arr.shape)
print(zeros_arr)

[[5 7 6]
 [1 8 4]
 [8 4 4]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Q.24
List= [5, 12, 9, 18, 3]
Square_List=[]
for value in List:
    if value%2 ==0:
        Square_List.append(value**2)
    else:
        Square_List.append(value)
print(Square_List)

[5, 144, 9, 324, 3]
